# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VB_Gui_drop_con_labels.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1094, 944)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1094, 944))
        MainWindow.setStyleSheet("#frame_svg{background-repeat: no-repeat;\n"
"border-image: url(:/immagine/_vb_interface_2.svg);\n"
" background-position: center;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(195, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.frame_svg_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_svg_2.sizePolicy().hasHeightForWidth())
        self.frame_svg_2.setSizePolicy(sizePolicy)
        self.frame_svg_2.setMinimumSize(QtCore.QSize(600, 400))
        self.frame_svg_2.setMaximumSize(QtCore.QSize(400, 400))
        self.frame_svg_2.setStyleSheet("QLabel{\n"
"    background-color: rgba(117, 255, 75, 100);}")
        self.frame_svg_2.setObjectName("frame_svg_2")
        self.label_21 = QtWidgets.QLabel(self.frame_svg_2)
        self.label_21.setGeometry(QtCore.QRect(389, 153, 101, 91))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_svg_2)
        self.label_22.setGeometry(QtCore.QRect(80, 40, 101, 91))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_svg_2)
        self.label_23.setGeometry(QtCore.QRect(250, 40, 101, 91))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_svg_2)
        self.label_24.setGeometry(QtCore.QRect(426, 40, 101, 91))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_svg_2)
        self.label_25.setGeometry(QtCore.QRect(424, 267, 101, 91))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_svg_2)
        self.label_26.setGeometry(QtCore.QRect(252, 268, 101, 91))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame_svg_2)
        self.label_27.setGeometry(QtCore.QRect(80, 267, 101, 91))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_svg_2)
        self.label_28.setGeometry(QtCore.QRect(115, 152, 101, 91))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.frame_svg = QtWidgets.QFrame(self.frame_svg_2)
        self.frame_svg.setGeometry(QtCore.QRect(0, 0, 600, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_svg.sizePolicy().hasHeightForWidth())
        self.frame_svg.setSizePolicy(sizePolicy)
        self.frame_svg.setMinimumSize(QtCore.QSize(600, 400))
        self.frame_svg.setMaximumSize(QtCore.QSize(400, 400))
        self.frame_svg.setStyleSheet("/*QLabel{\n"
"    background-color: rgba(117, 255, 75, 100);}*/")
        self.frame_svg.setObjectName("frame_svg")
        self.horizontalLayout_5.addWidget(self.frame_svg_2)
        spacerItem1 = QtWidgets.QSpacerItem(195, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMinimumSize(QtCore.QSize(256, 371))
        self.treeView.setMaximumSize(QtCore.QSize(400, 1024))
        self.treeView.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(False)
        self.horizontalLayout_6.addWidget(self.treeView)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.bot_rimuovi = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_rimuovi.sizePolicy().hasHeightForWidth())
        self.bot_rimuovi.setSizePolicy(sizePolicy)
        self.bot_rimuovi.setObjectName("bot_rimuovi")
        self.verticalLayout.addWidget(self.bot_rimuovi)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bot_aggiungi = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_aggiungi.sizePolicy().hasHeightForWidth())
        self.bot_aggiungi.setSizePolicy(sizePolicy)
        self.bot_aggiungi.setObjectName("bot_aggiungi")
        self.horizontalLayout_3.addWidget(self.bot_aggiungi)
        self.bot_nuovaCartella = QtWidgets.QPushButton(self.centralwidget)
        self.bot_nuovaCartella.setObjectName("bot_nuovaCartella")
        self.horizontalLayout_3.addWidget(self.bot_nuovaCartella)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bot_esci = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_esci.sizePolicy().hasHeightForWidth())
        self.bot_esci.setSizePolicy(sizePolicy)
        self.bot_esci.setObjectName("bot_esci")
        self.horizontalLayout.addWidget(self.bot_esci)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.bot_connetti = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_connetti.sizePolicy().hasHeightForWidth())
        self.bot_connetti.setSizePolicy(sizePolicy)
        self.bot_connetti.setObjectName("bot_connetti")
        self.horizontalLayout.addWidget(self.bot_connetti)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.bot_salva_preset = QtWidgets.QPushButton(self.centralwidget)
        self.bot_salva_preset.setObjectName("bot_salva_preset")
        self.horizontalLayout_4.addWidget(self.bot_salva_preset)
        self.bot_carica_preset = QtWidgets.QPushButton(self.centralwidget)
        self.bot_carica_preset.setObjectName("bot_carica_preset")
        self.horizontalLayout_4.addWidget(self.bot_carica_preset)
        self.bot_pulisci = QtWidgets.QPushButton(self.centralwidget)
        self.bot_pulisci.setObjectName("bot_pulisci")
        self.horizontalLayout_4.addWidget(self.bot_pulisci)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bot_impostazioni = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_impostazioni.sizePolicy().hasHeightForWidth())
        self.bot_impostazioni.setSizePolicy(sizePolicy)
        self.bot_impostazioni.setObjectName("bot_impostazioni")
        self.horizontalLayout_2.addWidget(self.bot_impostazioni)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1094, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuMenu.addAction(self.actionAbout)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_21.setText(_translate("MainWindow", "TextLabel"))
        self.label_22.setText(_translate("MainWindow", "TextLabel"))
        self.label_23.setText(_translate("MainWindow", "TextLabel"))
        self.label_24.setText(_translate("MainWindow", "TextLabel"))
        self.label_25.setText(_translate("MainWindow", "TextLabel"))
        self.label_26.setText(_translate("MainWindow", "TextLabel"))
        self.label_27.setText(_translate("MainWindow", "TextLabel"))
        self.label_28.setText(_translate("MainWindow", "TextLabel"))
        self.bot_rimuovi.setText(_translate("MainWindow", "rimuovi"))
        self.bot_aggiungi.setText(_translate("MainWindow", "file +"))
        self.bot_nuovaCartella.setText(_translate("MainWindow", "categoria +"))
        self.bot_esci.setText(_translate("MainWindow", "esci"))
        self.bot_connetti.setText(_translate("MainWindow", "Connetti"))
        self.bot_salva_preset.setText(_translate("MainWindow", "salva preset"))
        self.bot_carica_preset.setText(_translate("MainWindow", "carica preset"))
        self.bot_pulisci.setText(_translate("MainWindow", "pulisci"))
        self.bot_impostazioni.setText(_translate("MainWindow", "impostazioni"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

import vegeboard_svg_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

